import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const modulePath = process.env.PLAYWRIGHT_MODULE;
const { chromium } = await import(modulePath ? pathToFileURL(modulePath).href : 'playwright');
const base = process.env.GAME_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({ headless: true });
const errors = [];
try {
const first = await browser.newContext({ viewport: { width: 1366, height: 768 }, serviceWorkers: 'block' });
const page = await first.newPage(); page.on('pageerror', e => errors.push(e.message));
await page.goto(base); await page.waitForFunction(() => window.MC?.Ranking?.getStatus().online && MC.Ranking.getStatus().playerId);
await mkdir('test-results', { recursive: true });
await page.screenshot({ path: 'test-results/menu-desktop.png' });
await page.getByRole('button', { name: 'OPCIONES', exact: true }).click();
await page.locator('#opt-visual').selectOption('day');
await page.locator('#opt-music').fill('27');
assert.equal(await page.evaluate(() => MC.Save.loadOpts().visualMode), 'day');
assert.equal(await page.evaluate(() => MC.Save.loadOpts().music), 27);
assert.equal(await page.evaluate(() => MC.game.visualMode), 'day');
await page.getByRole('button', { name: 'VOLVER', exact: true }).click();
await page.getByRole('button', { name: 'NIVELES', exact: true }).click();
await page.locator('#diff-tabs button').first().click();
await page.locator('.level-card').first().click();
await page.locator('#nick-input').fill('RIKO-QA');
await page.locator('#nick-go').click();
await page.waitForFunction(() => MC.game._levelTicket && !MC.game._rankingStarting);
await page.waitForTimeout(5600);
await page.evaluate(async () => { await MC.game._finishLevelRanking(); });
const before = await page.evaluate(async () => MC.Ranking.getLeaderboard({ difficulty: 'easy', kind: 'level', level: 0 }));
assert.ok(before.entries.some(e => e.nickname === 'RIKO-QA'));
const second = await browser.newContext({ viewport: { width: 1280, height: 720 }, serviceWorkers: 'block' });
const remote = await second.newPage(); remote.on('pageerror', e => errors.push(e.message));
await remote.goto(base); await remote.waitForFunction(() => window.MC?.Ranking?.getStatus().online && MC.Ranking.getStatus().playerId);
const identityA = await page.evaluate(() => MC.Ranking.getStatus().playerId);
const identityB = await remote.evaluate(() => MC.Ranking.getStatus().playerId);
assert.notEqual(identityA, identityB);
await remote.evaluate(() => MC.Ranking.setNickname('CHALCHUAPA'));
const ticket = await remote.evaluate(async () => (await MC.Ranking.beginRun({ difficulty: 'easy', kind: 'level', level: 0 })).ticket);
await remote.waitForTimeout(5100);
await remote.evaluate(async ticket => MC.Ranking.finishRun(ticket, { activeMs: 5000, deaths: 0 }), ticket);
const after = await page.evaluate(async () => MC.Ranking.getLeaderboard({ difficulty: 'easy', kind: 'level', level: 0 }));
const a = after.entries.find(e => e.playerId === identityA), b = after.entries.find(e => e.playerId === identityB);
assert.ok(a && b); assert.ok(b.elapsedMs < a.elapsedMs); assert.ok(b.rank < a.rank);
await page.evaluate(() => { MC.game.suspendRun(); MC.menu.showScores(); });
await page.locator('#score-diff-tabs button').first().click();
await page.locator('#score-level').selectOption('0');
await page.waitForFunction(() => document.getElementById('score-table').textContent.includes('CHALCHUAPA'));
await page.screenshot({ path: 'test-results/shared-ranking.png' });
await page.locator('#score-scope').selectOption('local');
await page.waitForFunction(() => document.getElementById('score-status').textContent.includes('Solo este dispositivo'));
assert.ok(!(await page.locator('#score-table').textContent()).includes('CHALCHUAPA'));
assert.deepEqual(errors, []);
// Install the real PWA cache, then reload with the network unavailable.
const pwa = await browser.newContext({ viewport: { width: 1280, height: 720 } });
const offline = await pwa.newPage(); offline.on('pageerror', e => errors.push(e.message));
await offline.goto(base); await offline.waitForFunction(() => !!window.MC);
await offline.evaluate(async () => { await Promise.race([navigator.serviceWorker.ready, new Promise((_, reject) => setTimeout(() => reject(new Error('La caché offline no terminó de instalarse')), 20000))]); });
await offline.reload(); await offline.waitForFunction(() => !!navigator.serviceWorker.controller && !!window.MC);
await pwa.setOffline(true);
await offline.reload(); await offline.waitForFunction(() => !!window.MC && document.getElementById('boot-hint').classList.contains('hide'));
assert.equal(await offline.evaluate(() => MC.menu.elMenu.classList.contains('hidden')), false);
assert.deepEqual(errors, []);
console.log('Navegador: opciones persistentes, modo día, dos identidades independientes y PWA sin conexión verificadas. Un tiempo menor de Chalchuapa aparece en el primer dispositivo; récords locales separados.');
} finally { await browser.close(); }
